---
title: "stats"
output: html_document
date: "2024-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(stargazer)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(dotwhisker)
library(broom)
library(MASS)
library(ggeffects)
library(ggpubr)
library(ggplot2)
library(dplyr)
library(msm)
library(sandwich)
```

```{r}
mx_data <- read_csv("~/flu_imprinting/data/mx_data_final.csv", show_col_types = FALSE)
```

```{r}
reg_data <- mx_data %>%
  dplyr::select(c("season", "imprinted_strain", "flu_deaths", "total", "circulating_strain", "age_recode", "birth_year", "year_recode")) %>% 
  filter(season != "2020-2021" & imprinted_strain != "H1N1pdm09")

reg_data$imprinted_strain <- factor(reg_data$imprinted_strain, 
                                           levels = c("ambiguous", "pH1N1", "H1N1_alpha", "H1N1_beta", "H1N1_gamma",
                                                      "H2N2", "H3N2", "H1N1", "naive"))

reg_data$imprinted_strain <- relevel(factor(reg_data$imprinted_strain), ref = "H3N2")

reg_data$circulating_strain <- relevel(factor(reg_data$circulating_strain), ref = "H3N2")

reg_data$age_recode <- factor(reg_data$age_recode)

reg_data$season <- factor(reg_data$season)
```

```{r}
poisson_model <- glm(flu_deaths ~ circulating_strain*imprinted_strain +
                       season +
                       age_recode +
                       offset(log(total)),
                     family = poisson(link = "log"),
                     data = reg_data)

#options(max.print=100000)
#summary(poisson_model)
```

```{r}
save(poisson_model, file = "~/flu_imprinting/data/poisson_model.rda")
```

prediction plot
```{r}
marginal_effect <- predict_response(
  poisson_model,
  terms = c("circulating_strain", "imprinted_strain"),
  ci_level = 0.95,
  type = "count",
  condition = c(total = 100000),
  interval = "confidence") %>%
  dplyr::rename(circulating_strain = x, imprinted_strain = group) 

marginal_effect <- marginal_effect %>% 
  filter(imprinted_strain != "naive" & imprinted_strain != "H1N1pdm09")

marginal_effect$circulating_strain <- factor(marginal_effect$circulating_strain, 
                                             levels = c("H1N1", "H1N1pdm09", "H3N2", "ambiguous", "B"))

levels(marginal_effect$circulating_strain)[levels(marginal_effect$circulating_strain) == "ambiguous"] <- "Ambiguous"

marginal_effect$imprinted_strain <- factor(marginal_effect$imprinted_strain, 
                                           levels = c("ambiguous", "pH1N1", "H1N1_alpha", "H1N1_beta", "H1N1_gamma",
                                                      "H2N2", "H3N2", "H1N1", "H1N1pdm09", "naive"))

p_poiss=ggplot(marginal_effect, aes(circulating_strain, predicted, color = imprinted_strain)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width=0.5), 
                  alpha = 0.9, size = 0.6) +
  scale_y_log10(breaks=c(0.01, 0.1, 1), limits = c(0.003, 1.005), n.breaks = 4) +
  scale_color_manual(name = "Imprinted strain",
                     values = c(pH1N1 = "#ff6698",
                                H1N1_alpha = "#b70000", 
                                H1N1_beta = "#ff8900", 
                                H1N1_gamma = "#ECC905", 
                                H2N2 = "#95C90F", 
                                H3N2 = "#3683C3",
                                ambiguous = "#989898"),
                     labels = c(ambiguous = "Ambiguous",
                                pH1N1 = bquote(pH1N1["\u03b1"]  ),
                                H1N1_alpha = bquote(H1N1["\u03b1"]),
                                     H1N1_beta = bquote(H1N1["\u03b2"]),
                                     H1N1_gamma = bquote(H1N1["\u03b3"]))) +
  theme_bw() +
  labs(x = "Circulating strain", y = "Predicted influenza mortality rate") +
  theme(legend.justification = c(0, 1), legend.position = c(.01, 0.98),
        legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25),
        legend.title = element_text(size = 14),
        text = element_text(size = 16, family = "Helvetica"),
        plot.margin=unit(c(0.75, 0.25, 0.25, 0.25), "lines"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())
```


```{r}
ggsave(filename = "~/flu_imprinting/plots/final_figs/prediction_plot.png", 
       plot = p_poiss, height = 5, width = 8, dpi = 800, bg='#ffffff')
```


aggregate by imprinted strain
```{r}
age_cohort <- reg_data %>% filter(season != "2020-2021", !(imprinted_strain %in% c("naive", "H1N1pdm09"))) %>%
  mutate(death_rate = flu_deaths / total) %>%
  mutate(new_imprinted_strain = case_when(imprinted_strain == "pH1N1" ~ "pH1N1_H1N1_alpha",
                                          imprinted_strain == "H1N1_alpha" ~ "pH1N1_H1N1_alpha",
                                          imprinted_strain == "H1N1_beta" ~ "H1N1_beta_gamma",
                                          imprinted_strain == "H1N1_gamma" ~ "H1N1_beta_gamma",
                                          TRUE ~ as.character(imprinted_strain))) %>%
  group_by(new_imprinted_strain, age_recode) %>% summarize(mean_death_rate = mean(death_rate) * 100000,
                                                           sd_death_rate = sd(death_rate) * 100000,
                                                           n = n()) %>%
  mutate(upper = mean_death_rate + sd_death_rate/sqrt(n), lower = mean_death_rate - sd_death_rate/sqrt(n))

age_cohort$new_imprinted_strain <- factor(age_cohort$new_imprinted_strain, 
                                           levels = c("ambiguous", "pH1N1_H1N1_alpha", "H1N1_beta_gamma",
                                                      "H2N2", "H3N2"))

p_age_cohort <- ggplot(age_cohort, aes(x = as.numeric(age_recode), y = mean_death_rate, fill = new_imprinted_strain,
             color = new_imprinted_strain)) + geom_point(alpha = 0.8, shape = 1) +
  geom_errorbar(aes(ymin=(lower), ymax=(upper), group = new_imprinted_strain,
                    color = new_imprinted_strain), alpha = 0.6, width = 0.2)  +
  geom_smooth(method = "loess", linewidth = 0.8) +
  scale_y_continuous(trans = "log10", breaks = c(0.01, 0.10, 1.00, 10.0, 100), labels = c("0.01", "0.10", "1.00", "10.0", "100")) +
  scale_color_manual(name = "Imprinted strain  ", 
                     values = c("ambiguous" = "#989898",
                                pH1N1_H1N1_alpha = "#ff6698",
                                H1N1_beta_gamma = "#ff8900",
                                H2N2 = "#95C90F", 
                                H3N2 = "#3683C3"),
                     labels = c("ambiguous" = "Ambiguous",
                                pH1N1_H1N1_alpha = bquote(pH1N1["\u03b1"]/H1N1["\u03b1"]),
                                H1N1_beta_gamma = bquote(H1N1["\u03b2"]/H1N1["\u03b3"]))) +
  scale_fill_manual(values = c(ambiguous = "#989898",
                               pH1N1_H1N1_alpha = "#F68DBB",
                               H1N1_beta_gamma = "#FAA948",
                               H2N2 = "#ced07d", 
                               H3N2 = "#b4c9fe"),
                    guide = "none") +
  scale_x_continuous(n.breaks = 8) +
  labs(color = "", fill = "", x = "Age", y = "Mean influenza mortality rate") +
  theme_bw() +
  theme(legend.justification = c(0, 1), legend.position = c(.0115, 0.98),
        legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25),
        legend.title = element_text(size = 14),
        legend.key.size = unit(0.55, "cm"),
        text = element_text(size = 15, family = "Helvetica"),
        plot.margin=unit(c(0.5, 1, 1, 1.5), "lines"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank()) + 
  guides(color = guide_legend(override.aes = list(fill=NA)))
```

```{r}
ggsave(filename = "~/flu_imprinting/plots/mean_mortality_plot.png", p_age_cohort, height = 5, width = 7, dpi = 800)
```


incidence rate ratio table
```{r}
m1 <- poisson_model

cov.m1 <- vcovHC(m1, type="HC0")
std.err <- sqrt(diag(cov.m1))
r.est <- na.omit(cbind(Estimate = coef(m1, complete = FALSE), 
                 "Robust SE" = std.err,
                 "Pr(>|z|)" = 2 * pnorm(abs(coef(m1, complete = FALSE)/std.err), lower.tail = FALSE),
                 LL = coef(m1, complete = FALSE) - 1.96 * std.err,
                 UL = coef(m1, complete = FALSE) + 1.96 * std.err))

deltas <- lapply(1:length(coef(m1, complete = FALSE)), function(i) as.formula(paste0("~ exp(x", i, ")")))

s <- deltamethod(deltas, coef(m1, complete = FALSE), cov.m1)

# exponentiate estimates and confidence intervals, dropping p values
rexp.est <- exp(r.est[, -3])

# Replace SEs with delta method estimates
rexp.est[, "Robust SE"] <- s

round(rexp.est, 3)

```


Lee carter parameters for fig 1
```{r}
kt <- read_csv("~/flu_imprinting/data/lee_carter_kt.csv")
ax_bx <- read_csv("~/flu_imprinting/data/lee_carter_age_params.csv")
```

```{r}
kt_plot <- ggplot(kt, aes(x = year_recode, y = kt)) +
  geom_ribbon(aes(ymin = kt_lower, ymax = kt_upper), fill = "gray80") +
  geom_line() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        text = element_text(size = 15, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.margin=unit(c(0, 1, 0, 0.75), "lines"),
        axis.title.y = element_text(margin = margin(t = 0, r = -10, b = 0, l = 0))) +
  labs(x = NULL, y = bquote(k[t])) +
  scale_x_continuous(labels = c("1970", "1980", "1990", "2000", "2010", "2020"))

ax_plot <- ggplot(ax_bx, aes(x = age_recode, y = ax)) +
  geom_ribbon(aes(ymin = ax_lower, ymax = ax_upper), fill = "gray80") +
  geom_line() +
  theme_bw() +
  theme(text = element_text(size = 15, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.margin=unit(c(0, 0.4, 0.96, 1.275), "lines")) +
  labs(x = NULL, y = bquote(a[x])) +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100)) +
  scale_y_continuous(breaks = c(-15, -12, -9, -6))

bx_plot <- ggplot(ax_bx, aes(x = age_recode, y = bx)) +
  geom_ribbon(aes(ymin = bx_lower, ymax = bx_upper), fill = "gray80") +
  geom_line() +
  theme_bw() +
  theme(text = element_text(size = 15, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0))) +
  scale_y_continuous(n.breaks = 5) +#breaks = c(0, 0.003, 0.006, 0.009, 0.012, 0.015)) +
  labs(x = "Age", y = bquote(b[x]),
  plot.margin=unit(c(1, 1, 1, 1), "lines")) +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100))
```

plot of aggregated mortality compared to estimates
```{r}
mx_data_agg <- mx_data %>% 
  dplyr::select(c(age_recode, season, year_recode, total, flu_deaths, log_flu_mx_est, flu_mx))

mx_data_agg$lc_count <- exp(mx_data_agg$log_flu_mx_est) * mx_data_agg$total

mx_data_agg <- mx_data_agg %>% 
  group_by(season) %>% 
  summarise(est_deaths = sum(lc_count, na.rm = TRUE),
            deaths = sum(flu_deaths))

exposure = fread("~/flu_imprinting/data/Exposures_1x1.txt", skip = 1) %>%
  dplyr::select(c("Year", "Total")) %>%
  filter(Year %in% 1967:2022) %>%
  group_by(Year) %>% 
  summarise(total = sum(Total))
  
colnames(exposure) = tolower(colnames(exposure))
  
monthly_exposure <- exposure %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) %>%
    reframe(
      month = seq(min(date), max(date), by = "month"), 
      year = as.integer(format(month, format = "%Y")),
      across(
      .cols = c(total), 
      .fns = ~ {
        approx(date, .x, xout = month)$y
      }))

seasonal_exposure <- monthly_exposure %>%
    filter(as.numeric(sapply(str_split(month, "-",  n = 3), `[`, 2)) == 9) %>%
    mutate(season = paste0(year, "-", year+1)) %>%
    dplyr::select(c("season", "total", "year")) %>%
    filter(season != "1967-1968")

mx_data_agg <- mx_data_agg %>% 
  left_join(seasonal_exposure, by = "season")

mx_data_agg$total_flu_mx <- mx_data_agg$deaths / mx_data_agg$total * 100000
mx_data_agg$total_flu_mx_est <- mx_data_agg$est_deaths / mx_data_agg$total * 100000

mx_data_agg$log_total_flu_mx <- log(mx_data_agg$deaths / mx_data_agg$total * 100000)
mx_data_agg$log_total_flu_mx_est <- log(mx_data_agg$est_deaths / mx_data_agg$total * 100000)
```

```{r}
agg_plot = ggplot() +
  geom_point(data = mx_data_agg, 
             aes(x = year, y = exp(log_total_flu_mx_est), color = "Estimated"), alpha = 1, size = 3.25, shape = 17) +
  geom_point(data = mx_data_agg, 
             aes(x = year, y = exp(log_total_flu_mx), color = "Observed"), alpha = 1, size = 1.5) +
  scale_color_manual(name = NULL, values = c("Observed" = "#4f4f4f", "Estimated" = "#09d1db")) +
  labs(color = "", x = "Season", y = "Log influenza mortality rate") +
  scale_y_continuous(limits = c(0, 5.15), breaks = seq(0, 5, by = 1)) +
  theme_bw() +
  theme(legend.position = c(0.555, 0.98), legend.justification = c(0, 1), 
        legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25),
        legend.text = element_text(size = 12),
        legend.key.size = unit(0.3, "cm"),
        text = element_text(size = 15, family = "Helvetica"),
        axis.text.x = element_text(angle = 60, hjust = 1),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y = element_text(margin = margin(t = 0, r = 4, b = 0, l = 0)),
        plot.margin=unit(c(0.25, 1, 0, 1.5), "lines"))
```

```{r}
fig1 = ggarrange(p_age_cohort,
                 ggarrange(ax_plot, kt_plot,
                      ncol = 2,
                      labels = c("B", "C"),
                      font.label = list(size = 18, color = "black", family = "Helvetica"),
                      label.y = 0.95),
                 ggarrange(bx_plot, agg_plot,
                      ncol = 2,
                      labels = c("D", "E"),
                      font.label = list(size = 18, color = "black", family = "Helvetica"),
                      label.y = 0.95),
          nrow = 3,
          labels = "A",
          font.label = list(size = 18, color = "black", family = "Helvetica"), heights = c(1, 0.75, 0.85),
          label.y = 0.95)
```


```{r}
ggsave(filename = "~/flu_imprinting/plots/final_figs/fig1.png", plot = fig1, height = 9, width = 7,
       dpi = 800, bg='#ffffff')
```






