---
title: "add influenza surveillance data"
author: "Kylee Hoffman"
date: "2025-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(stringi)
library(imprinting)
library(lubridate)
library(janitor)
```

```{r}
source("~/influenza-imprinting/influenza-imprinting-public/code/utils.R")

load("~/influenza-imprinting/data/01.mortality_data.RData")
```

Flu surveillance data to get dominant strain
```{r}
strain_dominance_fun <- function() {
  # Use data on subtype prevalence to determine prominent strain in a year
  fread("~/influenza-imprinting/data/VIW_FNT.csv") %>%
    filter(COUNTRY_AREA_TERRITORY == "United States of America", MMWR_YEAR <= 2022) %>%
    dplyr::select(MMWR_WEEKSTARTDATE, AH1N12009, AH1, AH3, 
                  AOTHER_SUBTYPE, AOTHER_SUBTYPE_DETAILS, INF_B, INF_A) %>%
    mutate(across(-MMWR_WEEKSTARTDATE, ~ ifelse(is.na(.), 0, .)),
           H3N2 = if_else(str_detect(AOTHER_SUBTYPE_DETAILS, "H3N2"), AH3 + AOTHER_SUBTYPE,
                          AH3), # not repeating this for H1N1 - would not change anything
           year = as.numeric(substr(MMWR_WEEKSTARTDATE, 1, 4)),
           month = as.numeric(substr(MMWR_WEEKSTARTDATE, 6, 7)),
           season = case_when(#year == 2009 & month >= 4 ~ "2009-2010",
                              #year == 2009 & month < 4 ~ "2008-2009",
                              month >= 9 ~ paste0(year, "-", year + 1),
                              TRUE ~ paste0(year - 1, "-", year))) %>%
    group_by(season) %>%
    summarise(H1N1 = sum(AH1),
              H1N1pdm09 = sum(AH1N12009),
              H3N2 = sum(H3N2),
              B_all = sum(INF_B),
              A_all = sum(INF_A)) %>% 
    ungroup() %>%
    mutate(B_majority = ifelse(B_all > A_all, TRUE, FALSE),
           A_all = H3N2 + H1N1 + H1N1pdm09, # only sum flu A together for denom. when B is not dominant 
           B_pct = B_all / (A_all + B_all), # 3 B-dominated years, but only counting 2020-2021
           H3N2_pct = H3N2 / A_all,
           H1N1_pct = H1N1 / A_all,
           H1N1pdm09_pct = H1N1pdm09 / A_all) %>%
    mutate(circulating_strain = case_when(B_majority == TRUE ~ "B",
                                          H3N2_pct >= 0.7 ~ "H3N2",
                                          H1N1_pct >= 0.7 ~ "H1N1",
                                          H1N1pdm09_pct >= 0.7 ~ "H1N1pdm09",
                                          TRUE ~ "ambiguous")) %>%
    dplyr::select(season, circulating_strain)
}
```

manually digging through surveillance reports
some sources: 1970-1971: https://stacks.cdc.gov/view/cdc/283
1976-1977: https://stacks.cdc.gov/view/cdc/288
1979-1980: https://stacks.cdc.gov/view/cdc/290
```{r}
previous_strains <- data.frame(year = 1918:1995) %>% 
  mutate(season = paste0(year, "-", year + 1),
         circulating_strain = case_when(year %in% c(1918:1956, 1978, 1986) ~ "H1N1",
                                        year %in% 1957:1966 ~ "H2N2",
                                        year %in% c(1970, 1973, 1976, 1979, 
                                                    1981, 1985, 1992) ~ "B",
                                        year %in% c(1968, 1969, 1971, 1972,
                                                    1974, 1975, 1980, 1982,
                                                    1984, 1987, 1989, 1993, 1994) ~ "H3N2",
                                        year %in% c(1957, 1967, 1977, 1983, 
                                                    1988, 1990, 1991, 1995) ~ "ambiguous"))
```

```{r}
strain_dominance <- strain_dominance_fun() %>% 
  rbind(previous_strains[ , c("season", "circulating_strain")]) %>% 
  arrange(season) %>% 
  mutate(year = as.numeric(sapply(str_split(season, "-",  n = 2), `[`, 1)))
```


```{r}
cumulative_exposure <- expand.grid(year = 1918:2022, 
                                   birth_year = 1860:2020) %>% 
  filter(birth_year <= year & year - birth_year <= 108) %>% 
  right_join(strain_dominance, by = "year") %>% 
  arrange(birth_year, year) %>%
  group_by(birth_year) %>%
  mutate(seasons_survived = year - birth_year,
         H1N1_cumulative = lag(cumsum(circulating_strain %in% c("H1N1", "H1N1pdm09")), 
                               default = 0),  # sum H1N1 seasons in data
         H3N2_cumulative = lag(cumsum(circulating_strain == "H3N2"), default = 0),
         H2N2_cumulative = lag(cumsum(circulating_strain == "H2N2"), default = 0),
         B_cumulative = lag(cumsum(circulating_strain == "B"), default = 0)) %>%
  ungroup() %>% 
  mutate(H1N1_exposure = H1N1_cumulative / seasons_survived,
         H3N2_exposure = H3N2_cumulative / seasons_survived,
         H2N2_exposure = H2N2_cumulative / seasons_survived,
         B_exposure = B_cumulative / seasons_survived) %>% 
  filter(year %in% 1968:2020) %>% 
  dplyr::select(season, birth_year, H1N1_exposure, H3N2_exposure, H2N2_exposure, B_exposure)
```

imprinting probabilities
```{r}
imprint_probs <- get_imprinting_probabilities(observation_years = 1968:2022, countries = 'United States') %>%
  dplyr::select(-c("country"))

imprint_max_prob <- imprint_probs %>%
  group_by(birth_year, year) %>%
  filter(imprinting_prob == max(imprinting_prob)) %>%
  mutate(subtype = case_when(
    imprinting_prob < 0.7 & subtype != "naive" ~ "mixed",
    TRUE ~ subtype)) %>%
  mutate(imprinted_strain = case_when(
    birth_year %in% 1918:1920 & subtype == "A/H1N1" ~ "pH1N1",
    birth_year %in% 1921:1933 & subtype == "A/H1N1" ~ "H1N1_alpha",
    birth_year %in% 1934:1946 & subtype == "A/H1N1" ~ "H1N1_beta",
    birth_year %in% 1947:1956 & subtype == "A/H1N1" ~ "H1N1_gamma",
    birth_year %in% 1970:2008 & subtype == "A/H1N1" ~ "H1N1",
    birth_year >= 2009 & subtype == "A/H1N1" ~ "H1N1pdm09",
    subtype == "A/H2N2" ~ "H2N2",
    subtype == "A/H3N2" ~ "H3N2",
    TRUE ~ subtype))

names(imprint_max_prob)[names(imprint_max_prob) == "year"] <- "year_recode"

save(imprint_probs, file = "~/influenza-imprinting/data/imprinting_probabilities.RData")
```


```{r}
data <- mx_data %>%
  mutate(year_recode = as.numeric(sapply(str_split(season, "-",  n = 2), `[`, 1))) %>%  # first year of season
  left_join(strain_dominance, by = "season") %>% 
  left_join(imprint_max_prob[ , c("imprinted_strain", "birth_year", "year_recode")], 
            by = c("birth_year", "year_recode")) %>% 
  left_join(cumulative_exposure, by = c("birth_year", "season")) %>% 
  mutate(imprinted_strain = ifelse(birth_year < 1918, "unknown", imprinted_strain),
         age_recode = year_recode - birth_year) %>% 
  filter(season != "2021-2022")
```

```{r}
save(data, file = "~/influenza-imprinting/data/02.mortality_surveillance_data.RData")
#rm(list = ls())
```