---
title: "fig1"
author: "Kylee Hoffman"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(grid)
library(ggpubr)
library(tidyverse)
library(data.table)
library(scales)
library(cowplot)
library(StMoMo)
library(janitor)
```

```{r}
source("~/influenza-imprinting/influenza-imprinting-public/code/utils.R")

load("~/influenza-imprinting/influenza-imprinting-public/data/final_panel_data.RData")
load("~/influenza-imprinting/influenza-imprinting-public/data/lee_carter_parameters.RData")
```

```{r}
initial_cohort_size <- fread("~/influenza-imprinting/data/Exposures_1x1.txt", 
                                skip = 1) %>%
  clean_names(case = "lower_camel") %>% 
  filter(age == 0) %>%
  mutate(age = as.numeric(age),
         birth_year = year - age,
         initial_size = total) %>% 
  left_join(data %>% filter(age_recode == 20) %>% 
              dplyr::select(birth_year, imprinted_strain), 
            by = "birth_year", multiple = "first") %>% 
  filter(imprinted_strain %in% c("H3N2", "H2N2")) %>% 
  dplyr::select(birth_year, imprinted_strain, initial_size)
```


```{r}
deaths <- data %>%
  filter(age_recode %in% 12:45 & birth_year <= 1980 &
           imprinted_strain %in% c("H2N2", "H3N2")) %>%
  group_by(birth_year) %>%
  summarise(deaths5to45 = sum(flu_deaths, na.rm = TRUE)) %>% 
  left_join(initial_cohort_size, by = "birth_year") %>% 
  mutate(pct_dead = deaths5to45 / initial_size * 100) %>% 
#  group_by(imprinted_strain) %>%
#  summarise(pct_dead = sum(deaths5to45) / sum(initial_size) * 100)
  group_by(imprinted_strain) %>% 
  summarize(mean_pct_dead = mean(pct_dead),
            sd_pct_dead = sd(pct_dead),
            n = n()) %>%
  mutate(lower = mean_pct_dead - sd_pct_dead/sqrt(n),
         upper = mean_pct_dead + sd_pct_dead/sqrt(n),
         dead_p100k = mean_pct_dead * 1000,
         lower_p100k = lower * 1000,
         upper_p100k = upper * 1000)
```

mean cohort mortality by year
```{r}
fig1a <- data %>% 
  filter(season != "2020-2021", !(imprinted_strain %in% c("naive", "H1N1pdm09", "mixed"))) %>%
  mutate(new_imprinted_strain = case_when(imprinted_strain %in% c("pH1N1", "H1N1_alpha") ~ "pH1N1_H1N1_alpha",
                                          imprinted_strain %in% c("H1N1_beta", "H1N1_gamma") ~ "H1N1_beta_gamma",
                                          TRUE ~ as.character(imprinted_strain))) %>%
  group_by(new_imprinted_strain, year_recode) %>% 
  summarize(mean_death_rate = mean(flu_mx) * 100000,
            sd_death_rate = sd(flu_mx) * 100000,
            n = n()) %>%
  mutate(upper = mean_death_rate + sd_death_rate/sqrt(n), lower = mean_death_rate - sd_death_rate/sqrt(n)) %>% 
  ungroup() %>% 
  mutate(new_imprinted_strain = factor(new_imprinted_strain, 
                                       levels = c("unknown", "pH1N1_H1N1_alpha", "H1N1_beta_gamma", "H2N2", "H3N2", "mixed"))) %>% 
  ggplot(aes(x = as.numeric(year_recode), y = mean_death_rate, fill = new_imprinted_strain,
             color = new_imprinted_strain)) + geom_point(alpha = 0.8, shape = 1) +
  geom_errorbar(aes(ymin=(lower), ymax=(upper), group = new_imprinted_strain,
                    color = new_imprinted_strain), alpha = 0.8, width = 0.2)  +
  geom_smooth(method = "loess", linewidth = 0.6, alpha = 0.5) +
  scale_y_continuous(trans = "log10", breaks = c(0.01, 0.10, 1.00, 10.0, 100), labels = c("0.01", "0.10", "1.00", "10.0", "100")) +
  scale_color_manual(name = "Imprinted strain  ", 
                     values = c(mixed = "#989898",
                                unknown = "#555",
                                pH1N1_H1N1_alpha = "#ff6698",
                                H1N1_beta_gamma = "#ff8900",
                                H2N2 = "#95C90F", 
                                H3N2 = "#3683C3"),
                     labels = c("mixed" = "Mixed",
                                "unknown" = "Unknown",
                                pH1N1_H1N1_alpha = bquote(pH1N1["\u03b1"]/H1N1["\u03b1"]),
                                H1N1_beta_gamma = bquote(H1N1["\u03b2"]/H1N1["\u03b3"]))) +
  scale_fill_manual(values = c(mixed = "#989898",
                               unknown = "#555",
                               pH1N1_H1N1_alpha = "#F68DBB",
                               H1N1_beta_gamma = "#FAA948",
                               H2N2 = "#ced07d", 
                               H3N2 = "#b4c9fe"),
                    guide = "none") +
  labs(color = "", fill = "", x = "Influenza season", y = "Mean influenza mortality rate") +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 15, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.margin=margin(r = 0.75, l = 0.25, t = 0.3, unit = "lines")) + 
  coord_cartesian(xlim = c(1969, 2018))
```

```{r}
fig1b <- data %>% 
  filter(season != "2020-2021", !(imprinted_strain %in% c("naive", "mixed", "H1N1pdm09"))) %>%
  mutate(new_imprinted_strain = case_when(imprinted_strain %in% c("pH1N1", "H1N1_alpha") ~ "pH1N1_H1N1_alpha",
                                          imprinted_strain %in% c("H1N1_beta", "H1N1_gamma") ~ "H1N1_beta_gamma",
                                          TRUE ~ as.character(imprinted_strain))) %>%
  group_by(new_imprinted_strain, age_recode) %>% 
  summarize(mean_rate = mean(flu_mx) * 100000,
            mean_sd = sd(flu_mx) * 100000,
            n = n()) %>%
  mutate(upper = mean_rate + mean_sd/sqrt(n), lower = mean_rate - mean_sd/sqrt(n)) %>%
  ungroup() %>% 
  mutate(new_imprinted_strain = factor(new_imprinted_strain, 
                                       levels = c("unknown", "pH1N1_H1N1_alpha", "H1N1_beta_gamma", 
                                                  "H2N2", "H3N2", "mixed"))) %>% 
  ggplot(aes(x = as.numeric(age_recode), y = mean_rate, fill = new_imprinted_strain,
             color = new_imprinted_strain)) + geom_point(alpha = 0.8, shape = 1) +
  geom_errorbar(aes(ymin=(lower), ymax=(upper), group = new_imprinted_strain,
                    color = new_imprinted_strain), alpha = 0.6, width = 0.2)  +
  geom_smooth(method = "loess", linewidth = 0.8) +
  scale_y_continuous(trans = "log10", breaks = c(0.01, 0.10, 1.00, 10.0, 100), 
                     labels = c("0.01", "0.10", "1.00", "10.0", "100")) +
  scale_color_manual(name = "Imprinted strain  ", 
                     values = c(mixed = "#989898",
                                unknown = "#555",
                                pH1N1_H1N1_alpha = "#ff6698",
                                H1N1_beta_gamma = "#ff8900",
                                H2N2 = "#95C90F", 
                                H3N2 = "#3683C3"),
                     labels = c(mixed = "Mixed",
                                unknown = "Unknown",
                                pH1N1_H1N1_alpha = bquote(pH1N1["\u03b1"]/H1N1["\u03b1"]),
                                H1N1_beta_gamma = bquote(H1N1["\u03b2"]/H1N1["\u03b3"]))) +
  scale_fill_manual(values = c(mixed = "#989898",
                               unknown = "#555",
                               pH1N1_H1N1_alpha = "#F68DBB",
                               H1N1_beta_gamma = "#FAA948",
                               H2N2 = "#ced07d", 
                               H3N2 = "#b4c9fe"),
                    guide = "none") +
  scale_x_continuous(n.breaks = 8) +
  labs(color = "", fill = "", x = "Age", y = "Mean influenza mortality rate") +
  theme_bw() +
  theme(legend.justification = c(0, 1), legend.position = c(.0115, 0.98),
        legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25),
        legend.title = element_text(size = 14),
        legend.key.size = unit(0.55, "cm"),
        text = element_text(size = 15, family = "Helvetica"),
        plot.margin=margin(r = 0.75, l = 0.25, b = 0.3, unit = "lines"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank()) + 
  guides(color = guide_legend(override.aes = list(fill=NA)))
```


```{r}
fig1 <- ggarrange(NULL, fig1a, NULL, fig1b,
          ncol = 1, nrow = 4, heights = c(0.05, 1, 0.05, 1),
          labels = c("", "A", "", "B"), label.y = 1.06, label.x = 0.0275,
          font.label = list(size = 18, color = "black", family = "Helvetica"))
```

```{r}
ggsave(filename = "~/influenza-imprinting/plots/final_figs/fig1.png", 
       plot = fig2, height = 7, width = 6.5, dpi = 800, bg='#ffffff')
```



```{r}
A <- ggplot(lee_carter_parameters$ax_bx.df, aes(x = age_recode, y = ax)) +
  geom_ribbon(aes(ymin = ax_lower, ymax = ax_upper), fill = "gray80") +
  geom_line() +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100)) +
  scale_y_continuous(breaks = c(-15, -12, -9, -6)) +
  labs(x = "", y = bquote(a[x])) +
  theme_bw() +
  theme(text = element_text(size = 16, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y = element_text(margin = margin(t = 0, r = -5, b = 0, l = -1)),
        axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
        plot.margin=margin(l = 1.25, t = 1, b = -0.35, unit = "lines"))
```

```{r}
B <- lee_carter_parameters$kt.df %>% 
  left_join(data[, c("year_recode", "circulating_strain")], 
            by = "year_recode", multiple = "first") %>% 
  ggplot(aes(x = year_recode, y = kt)) +
  geom_errorbar(aes(ymin = kt_lower, ymax = kt_upper), width = 0.9, linewidth = 0.4) + #, fill = "gray30") +
  geom_line(linewidth = 0.2, alpha = 0.5) +
  geom_point(aes(fill = circulating_strain), color = "black", shape = 21,
             size = 2) +
  scale_x_continuous(breaks = seq(1970, 2020, by = 10)) +
    scale_fill_manual(name = "Circulating Strain",
                    values = c("H3N2" = "#69DEF5",
                               "H1N1" = "#F7826A",
                               "H1N1pdm09" = "#FF8FF3",
                               "B" = "#D7E843",
                               "ambiguous" = "#BF8FFF"),
                    labels = c("ambiguous" = "Ambiguous")) +
  labs(x = "", y = bquote(k[t])) +
  coord_cartesian(xlim = c(1969, 2019), ylim = c(-190, 190)) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 60, hjust = 1),
        text = element_text(size = 16, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y = element_text(margin = margin(t = 0, r = -5, b = 0, l = -1)),
        axis.title.x = element_text(margin = margin(t = 0, r = 0, b = 0, l = 0)),
        plot.margin=margin(l = 0.25, r = 0.5, b = -0.25, t = 1, unit = "lines"))
```


```{r}
C <- ggplot(lee_carter_parameters$ax_bx.df, aes(x = age_recode, y = bx)) +
  geom_ribbon(aes(ymin = bx_lower, ymax = bx_upper), fill = "gray80") +
  geom_line() +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100)) +
  scale_y_continuous(n.breaks = 5) +
  theme_bw() +
  theme(text = element_text(size = 16, family = "Helvetica"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.margin=margin(r = 0.1, t = -0.3, b = 0.1, l = 0.25, unit = "lines"),
        panel.background = element_blank(),
        axis.title.y = element_text(margin = margin(t = 0, r = -5, b = 0, l = -1)),
        axis.title.x = element_text(margin = margin(t = 20, r = 0, b = -0.5, l = 0))) +
  labs(x = "Age", y = bquote(b[x]))
```

```{r}
D <- data %>% 
  group_by(year_recode) %>% 
  reframe(deaths_fitted = sum(flu_deaths_fitted, na.rm = TRUE),
            deaths_obs = sum(flu_deaths, na.rm = TRUE),
            exposure = sum(total, na.rm = TRUE)) %>% 
  mutate(total_flu_mx = deaths_obs / exposure * 100000,
         total_flu_mx_fitted = deaths_fitted / exposure * 100000) %>% 
  ggplot() +
  geom_point(aes(x = year_recode, y = total_flu_mx_fitted, color = "Fitted"), 
             alpha = 1, size = 3.25, shape = 17) +
  geom_point(aes(x = year_recode, y = total_flu_mx, color = "Observed"), alpha = 1, size = 1.5) +
  scale_color_manual(name = NULL, values = c("Observed" = "#4f4f4f", "Fitted" = "#09d1db")) +
  labs(color = "", x = "Season", y = "Influenza deaths per 100,000") +
  scale_y_continuous(limits = c(0, 5.15), breaks = seq(0, 5, by = 1)) +
  theme_bw() +
  theme(legend.position = c(0.68, 0.98), legend.justification = c(0, 1), 
        legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25),
        legend.text = element_text(size = 12), legend.key.size = unit(0.3, "cm"),
        text = element_text(size = 16, family = "Helvetica"),
        axis.text.x = element_text(angle = 60, hjust = 1, margin = margin(t = -0.5)),
        axis.title.y = element_text(margin = margin(t = 0, r = 4, b = 0, l = 0)),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(),
        plot.margin=margin(l = 2, r = 0.375, t = -0.3, b = 0.1, unit = "lines"))
```

```{r}
fig2 <- ggarrange(ggarrange(NULL),
                  ggarrange(A, B,
                    ncol = 2,
                    labels = c("A", "B"),
                    font.label = list(size = 18, color = "black", 
                                      family = "Helvetica"), 
                    label.y = 1.04, label.x = 0.05),
        ggarrange(C, D,
                  ncol = 2,
                  labels = c("C", "D"),
                  font.label = list(size = 18, color = "black", family = "Helvetica"),
                  label.y = 1.075, label.x = 0.05),
                  ncol = 1, nrow = 3, heights = c(0.05, 1, 1),
                 font.label = list(size = 18, color = "black", family = "Helvetica"))

ggsave(filename = "~/influenza-imprinting/fig2.jpg",#~/influenza-imprinting/plots/final_figs/fig2.png", 
       plot = fig2, height = 8, width = 9, dpi = 800, bg='#ffffff')
```

```{r}
D <- data %>% 
  group_by(year_recode) %>% 
  reframe(deaths_fitted = sum(flu_deaths_fitted, na.rm = TRUE),
          deaths_obs = sum(flu_deaths, na.rm = TRUE),
          exposure = sum(total, na.rm = TRUE),
          circulating_strain = unique(circulating_strain)) %>% 
  mutate(total_flu_mx = deaths_obs / exposure * 100000,
         total_flu_mx_fitted = deaths_fitted / exposure * 100000,
         circulating_strain = factor(circulating_strain, 
                                     levels = c("B", "H3N2", "H1N1", "H1N1pdm09", "ambiguous"))) %>% 
  ggplot() +
  geom_point(aes(x = year_recode, y = total_flu_mx_fitted, fill = "Fitted"),
             shape = 17, size = 3.5, color = "gray40",
             key_glyph = lower_triangle) +
  geom_point(aes(x = year_recode, y = total_flu_mx, fill = circulating_strain),
             color = "black", shape = 21, size = 2.25, alpha = 0.9) +
  scale_fill_manual(name = "Circulating Strain",
                    values = c("Fitted" = "gray40", 
                               "H3N2" = "#69DEF5",
                               "H1N1" = "#F7826A",
                               "H1N1pdm09" = "#FF8FF3",
                               "B" = "#D7E843",
                               "ambiguous" = "#BF8FFF"),
                    labels = c("Fitted" = "Fitted",
                               "B" = "B",
                               "ambiguous" = "Ambiguous")) +
  labs(x = "Season", y = "Influenza deaths per 100,000") +
  coord_cartesian(ylim = c(0.15, 5.25)) +
  theme_bw() +
  guides(fill = guide_legend(ncol = 2,
                             override.aes = list(shape = c(21, 21, 21, 21, 21, 17),
                                                 size = c(2.25, 2.25, 2.25, 2.25, 2.25, 3)),
                             keyheight = unit(0.425, "cm"))) +
  theme(legend.position = c(0.475, 0.98), legend.justification = c(0, 1), 
      legend.background = element_rect(color = "black", fill = "white", linewidth = 0.25), legend.title = element_text(size = 14),
      legend.spacing.y = unit(1, 'cm'), legend.spacing.x = unit(0.5, 'cm'),
      legend.text = element_text(size = 12), legend.key.size = unit(0, "cm"),
      legend.margin = margin(t = 2.5, r = 3, b = 2.5, l = 3, unit = "pt"),
      text = element_text(size = 16, family = "Helvetica"),
      axis.text.x = element_text(angle = 60, hjust = 1, margin = margin(t = -0.5)),
      axis.title.y = element_text(margin = margin(t = 0, r = 4, b = 0, l = 0)),
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      plot.margin=margin(l = 1.25, r = 0.375, t = -0.3, b = 0.1, unit = "lines"))
```


